# Generated by Django 5.1.3 on 2024-11-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
