# Generated by Django 5.1.3 on 2024-11-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0002_remove_vehicle_area_remove_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='passengers',
            new_name='capacity',
        ),
    ]
