# Generated by Django 5.1.3 on 2024-11-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0004_alter_vehicle_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='province',
            field=models.ForeignKey(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='car_dealer_portal.area'),
        ),
    ]
