# Generated by Django 5.1.3 on 2024-11-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0006_remove_vehicle_city_remove_vehicle_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealer_portal.cardealer'),
        ),
    ]
