# Generated by Django 5.1.3 on 2024-11-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0007_alter_vehicle_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='car_photo_1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='car_photo_2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='car_photo_3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='car_photo_4',
        ),
    ]
